# This workflow will install Python dependencies with Python poetry and run tests with unittests.
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Tests

on:
  push:
    paths-ignore: 
      - website/**
      - assets/**
    branches: 
      - main
      - develop
  pull_request:
    branches: 
      - main
      - develop

jobs:
  ubuntu:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.6", "3.7", "3.8", "3.9", "3.10"]

    steps:
    - uses: actions/checkout@v2
    - uses: snok/install-poetry@v1.3.0
    - name: Set up Python ${{ matrix.python-version }} on Ubuntu
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Tests on Ubuntu
      run: |
        poetry install
        cd tests
        poetry run pytest

  windows:
    runs-on: windows-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.6", "3.7", "3.8", "3.9", "3.10"]

    steps:
    - uses: actions/checkout@v2
    - uses: snok/install-poetry@v1.3.0
    - name: Set up Python ${{ matrix.python-version }} on Windows
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Tests on Windows
      run: |
        poetry install
        cd tests
        poetry run pytest tests
    - name: Tests PREFS resources
      run: |
        ls
        poetry run prefs
